---
title: "R Notebook"
output: html_notebook
---

# MR Workflow:

```{r}
library(TwoSampleMR) 
library(tidyverse) 
library(MendelianRandomization)
```

```{r}
LDL <- system.file("extdata", "LDL_tophits.txt", package = "TwoSampleMR")
HF <- system.file("extdata", "HFdata.txt", package = "TwoSampleMR")
LDL
```

```{r}
LDL_exp_data <- read_exposure_data(LDL)
```

```{r}
options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')
LDL_clump <- clump_data(LDL_exp_data, clump_r2 = 0.01, pop = "EUR")
```

```{r}
HF_out_data <- read_outcome_data(HF, snps = LDL_clump$SNP)
```

```{r}
hd <- harmonise_data(LDL_clump, HF_out_data, action = 2) %>%
  as_tibble() %>%
  filter(pval.outcome > 5e-8, eaf.outcome > 0.05, eaf.exposure > 0.05)
```

```{r}
results <- mr(hd)
results$Lower_CI <- results$b - 1.96 * results$se
results$Upper_CI <- results$b + 1.96 * results$se
results
```

# Sensitivity Analyses:

```{r}
mr_pleiotropy_test(hd)
```

```{r}
heterogeneity_test <- mr_heterogeneity(hd)
heterogeneity_test
```

```{r}
plot1 <- mr_scatter_plot(results,hd)
plot1
```

```{r}
res_single <- mr_singlesnp(hd)
plot2 <- mr_forest_plot(res_single)
plot2
```

```{r}
res_loo <- mr_leaveoneout(hd)
plot3 <- mr_leaveoneout_plot(res_loo)
plot3
```

```{r}
plot4 <- mr_funnel_plot(res_single)
plot4
```

# Robust IVW estimate:

```{r}
mrdata <- mr_input(bx = hd$beta.exposure, bxse = hd$se.exposure, by = hd$beta.outcome, byse = hd$se.outcome, snps = hd$SNP)

```

```{r}
mrresult <- result_ivw <- MendelianRandomization::mr_ivw(mrdata, robust = TRUE, penalized = TRUE)
mrresult
```
